
 workflows:
     android-workflow:
       name: Build Android APK
       max_build_duration: 20
       environment:
         android: true
       scripts:
         - name: Build APK
           script: ./gradlew assembleRelease
       artifacts:
         - app/build/outputs/**/*.apk