workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      groups:
        - android-keys
      java: "17"
    scripts:
      - name: Set Gradle Permissions
        script: chmod +x ./gradlew
      - name: Clean Project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
